# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to=settings.AUTH_USER_MODEL),
        ),
    ]
