# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('account', '0002_auto_20171227_0039'),
        ('deadlines', '0002_auto_20171118_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='participants', to='account.Profile'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='teams', to='teams.Team'),
        ),
    ]
