# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.ManyToManyField(blank=True, to='teams.Team'),
        ),
    ]
